wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698110746.876607
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 13
      - 19
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 100
num_epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
drop_rate:
  desc: null
  value: 0.5
weight_decay:
  desc: null
  value: 0
