python3 run_mlp.py -n 2 -a R -l M
python3 run_mlp.py -n 2 -a Si -l M
python3 run_mlp.py -n 2 -a Se -l M
python3 run_mlp.py -n 2 -a Ge -l M
python3 run_mlp.py -n 2 -a Sw -l M
python3 run_mlp.py -n 2 -a R -l S
python3 run_mlp.py -n 2 -a Si -l S
python3 run_mlp.py -n 2 -a Se -l S
python3 run_mlp.py -n 2 -a Ge -l S
python3 run_mlp.py -n 2 -a Sw -l S
python3 run_mlp.py -n 2 -a R -l H
python3 run_mlp.py -n 2 -a Si -l H
python3 run_mlp.py -n 2 -a Se -l H
python3 run_mlp.py -n 2 -a Ge -l H
python3 run_mlp.py -n 2 -a Sw -l H
python3 run_mlp.py -n 2 -a R -l F
python3 run_mlp.py -n 2 -a Si -l F
python3 run_mlp.py -n 2 -a Se -l F
python3 run_mlp.py -n 2 -a Ge -l F
python3 run_mlp.py -n 2 -a Sw -l F
